version: '3.8'
services: 
  openfire:
    build:
      context: .
      dockerfile: Dockerfile
      cache_from: 
        - alpine:latest
    image: openfire:latest
    restart: always
    container_name: openfire
    ports:
      - "5222:5222/tcp"
      - "5223:5223/tcp"
      - "5229:5229/tcp"
      - "5262:5262/tcp"
      - "5263:5263/tcp"
      - "5275:5275/tcp"
      - "5276:5276/tcp"
      - "7070:7070/tcp"
      - "7443:7443/tcp"
      - "7777:7777/tcp"
      - "9090:9090/tcp"
      - "9091:9091/tcp"
    volumes:
      - ofsyslog:/var/log
      - oflogs:/var/lib/openfire/logs
      - ofconf:/var/lib/openfire/conf
      - oflib:/var/lib/openfire/lib
      - ofnewcerts:/var/lib/openfire/resources/security/hotdeploy

volumes:
  ofsyslog:
    driver: local
    driver_opts:
       o: bind
       type: none
       device: /srv/docker/openfire/syslog
  oflogs:
    driver: local
    driver_opts:
       o: bind
       type: none
       device: /srv/docker/openfire/logs
  oflib:
    driver: local
    driver_opts:
       o: bind
       type: none
       device: /srv/docker/openfire/lib
  ofconf:
    driver: local
    driver_opts:
       o: bind
       type: none
       device: /srv/docker/openfire/conf
  ofnewcerts:
    driver: local
    driver_opts:
       o: bind
       type: none
       device: /srv/docker/openfire/newcerts
       
