version: '3.8'
services: 
  openfire:
    build:
      context: .
      dockerfile: Dockerfile
      cache_from: 
        - alpine:latest
    image: sheldonrobinson/openfire:wood-dragon.1
    restart: always
    container_name: ofkonnek 
    ports:
      - "5222:5222/tcp"
      - "5223:5223/tcp"
      - "5229:5229/tcp"
      - "5262:5262/tcp"
      - "5263:5263/tcp"
      - "5275:5275/tcp"
      - "5276:5276/tcp"
      - "7070:7070/tcp"
      - "7443:7443/tcp"
      - "7777:7777/tcp"
      - "9090:9090/tcp"
      - "9091:9091/tcp"
    volumes:
      - /srv/docker/openfire/syslog:/var/log
      - /srv/docker/openfire/logs:${OPENFIRE_HOME}/logs
      - /srv/docker/openfire/security/hotdeploy:${OPENFIRE_HOME}/resources/security/hotdeploy
